//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 02:12:30 PM CET 
//


package fp.forevo.xml.map;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xClassName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xClassName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Button"/>
 *     &lt;enumeration value="TextBox"/>
 *     &lt;enumeration value="ComboBox"/>
 *     &lt;enumeration value="Window"/>
 *     &lt;enumeration value="Image"/>
 *     &lt;enumeration value="Element"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xClassName")
@XmlEnum
public enum XClassName {

    @XmlEnumValue("Button")
    BUTTON("Button"),
    @XmlEnumValue("TextBox")
    TEXT_BOX("TextBox"),
    @XmlEnumValue("ComboBox")
    COMBO_BOX("ComboBox"),
    @XmlEnumValue("Window")
    WINDOW("Window"),
    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("Element")
    ELEMENT("Element");
    private final String value;

    XClassName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XClassName fromValue(String v) {
        for (XClassName c: XClassName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
