//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 04:26:39 PM CEST 
//

package fp.forevo.xml.map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for xImage complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="xImage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="imgRecognition" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ocrText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textArea" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="similarity" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="offsetX" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="offsetY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xImage")
public class XImage {

	@XmlAttribute(name = "imgRecognition", required = true)
	protected boolean imgRecognition;
	@XmlAttribute(name = "fileName", required = true)
	protected String fileName;
	@XmlAttribute(name = "ocrText")
	protected String ocrText;
	@XmlAttribute(name = "textArea")
	protected String textArea;
	@XmlAttribute(name = "similarity")
	protected Float similarity;
	@XmlAttribute(name = "offsetX")
	protected Integer offsetX;
	@XmlAttribute(name = "offsetY")
	protected Integer offsetY;
	@XmlAttribute(name = "tag")
	protected String tag;

	/**
	 * Gets the value of the imgRecognition property.
	 * 
	 */
	public boolean isImgRecognition() {
		return imgRecognition;
	}

	/**
	 * Sets the value of the imgRecognition property.
	 * 
	 */
	public void setImgRecognition(boolean value) {
		this.imgRecognition = value;
	}

	/**
	 * Gets the value of the fileName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * Sets the value of the fileName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFileName(String value) {
		this.fileName = value;
	}

	/**
	 * Gets the value of the ocrText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOcrText() {
		return ocrText;
	}

	/**
	 * Sets the value of the ocrText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOcrText(String value) {
		this.ocrText = value;
	}

	/**
	 * Gets the value of the textArea property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextArea() {
		return textArea;
	}

	/**
	 * Sets the value of the textArea property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextArea(String value) {
		this.textArea = value;
	}

	/**
	 * Gets the value of the similarity property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSimilarity() {
		return similarity;
	}

	/**
	 * Sets the value of the similarity property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSimilarity(Float value) {
		this.similarity = value;
	}

	/**
	 * Gets the value of the offsetX property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getOffsetX() {
		return offsetX;
	}

	/**
	 * Sets the value of the offsetX property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setOffsetX(Integer value) {
		this.offsetX = value;
	}

	/**
	 * Gets the value of the offsetY property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getOffsetY() {
		return offsetY;
	}

	/**
	 * Sets the value of the offsetY property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setOffsetY(Integer value) {
		this.offsetY = value;
	}

	/**
	 * Gets the value of the tag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * Sets the value of the tag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTag(String value) {
		this.tag = value;
	}

}
