//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.24 at 11:02:52 AM CEST 
//


package fp.forevo.xml.map;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Window" type="{TestObjectMap}xWindow" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="parentClassName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scriptClassPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errState" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="errDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "window"
})
@XmlRootElement(name = "xTestObjectMap")
public class XTestObjectMap {

    @XmlElement(name = "Window")
    protected List<XWindow> window;
    @XmlAttribute(name = "parentClassName")
    protected String parentClassName;
    @XmlAttribute(name = "scriptClassPath")
    protected String scriptClassPath;
    @XmlAttribute(name = "errState")
    protected Integer errState;
    @XmlAttribute(name = "errDescription")
    protected String errDescription;

    /**
     * Gets the value of the window property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the window property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWindow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XWindow }
     * 
     * 
     */
    public List<XWindow> getWindow() {
        if (window == null) {
            window = new ArrayList<XWindow>();
        }
        return this.window;
    }

    /**
     * Gets the value of the parentClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentClassName() {
        return parentClassName;
    }

    /**
     * Sets the value of the parentClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentClassName(String value) {
        this.parentClassName = value;
    }

    /**
     * Gets the value of the scriptClassPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptClassPath() {
        return scriptClassPath;
    }

    /**
     * Sets the value of the scriptClassPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptClassPath(String value) {
        this.scriptClassPath = value;
    }

    /**
     * Gets the value of the errState property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getErrState() {
        return errState;
    }

    /**
     * Sets the value of the errState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setErrState(Integer value) {
        this.errState = value;
    }

    /**
     * Gets the value of the errDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrDescription() {
        return errDescription;
    }

    /**
     * Sets the value of the errDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrDescription(String value) {
        this.errDescription = value;
    }

}
